name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.8"
          enable-cache: true


      - name: Set up Python
        run: uv python install 3.9

      - name: Install dependencies
        run: uv sync --locked

      - name: Run Ruff Check
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git fetch origin main
            CHANGED_FILES=$(git diff --name-only origin/main...HEAD -- '*.py')
            if [ -n "$CHANGED_FILES" ]; then
              uv run ruff check $CHANGED_FILES
            fi
          else
            uv run ruff check .
          fi

      - name: Run Ruff Format
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git fetch origin main
            CHANGED_FILES=$(git diff --name-only origin/main...HEAD -- '*.py')
            if [ -n "$CHANGED_FILES" ]; then
              uv run ruff format --check $CHANGED_FILES
            fi
          else
            uv run ruff format --check .
          fi